### ISSUE TITLE
docker-compose and build objects 

### ISSUE THREAD

**Issue by davidmarkclements** [apparatus/fuge#158]
given a service in the `docker-compose.yml` file like:

```yaml
  foo:
    build:
      context: ../service-path
      args:
        foo: 'some arg'
```

This will result in 

```
compiling...
Path must be a string. Received { context: '../service-path',
  args: { foo: 'some arg' } }
```
