### ISSUE TITLE
fuge 2.0.0 cant't set environment process env

### ISSUE THREAD

**Issue by Remexllee** [apparatus/fuge#161]
I found out an issue when I update fuge to 2.0.0, my `environment` parameter can't be set into process env.

The yml file below work well in fuge 1.0.0
But in 2.0.0, there is no env for `BOOTSTRAP_ENV` and `BOOTSTRAP_DC`

```
fuge_global:
  ...
  dns_host: 127.0.0.1
  monitor_excludes: 
    - '**/node_modules/**'
  environment:
   - "BOOTSTRAP_ENV=abc"
   - "BOOTSTRAP_DC=def"
   ...
```
