### ISSUE TITLE
Fuge build not running Dockerfile RUN command

### ISSUE THREAD

**Issue by feugy** [apparatus/fuge#54]
In your fuge project, we have a node service that requires to be built. 

Here is the `Dockerfile`:
```
FROM node
ADD . /
RUN npm install
RUN npm run build
CMD npm start
```

And the global `compose-dev.yml`:
```
mesh_base:
  build: ../mesh-base/
  container_name: mesh-base

fast_ui:
  build: ../fast-ui/
  container_name: fast-ui

fast_service:
  build: ../fast-service/
  container_name: fast-service

concorda:
  build: ../concorda/
  container_name: concorda

concorda_dashboard:
  build: ../concorda-dashboard/
  container_name: concorda-dashboard
```

The build output is :
```
$ fuge build fuge/compose-dev.yml
building...
building: mesh_base
building: fast_ui
building: fast_service
building: concorda
building: concorda_dashboard
```

But the expected `npm install` and `npm run build` output folders still don't exist. 
How can I check what build as effectively done ?
