### ISSUE TITLE
Issues when running docker from fuge

### ISSUE THREAD

**Issue by vigneshnrfs** [apparatus/fuge#78]
I am trying to the mongoDb docker image from the fuge shell.

```
mongo:
  image: mongo:3.2
  constainer_name: mongo
  ports:
     - 10012:27017
  volumes:
     - db:/data/db
```

When I run fuge shell and start mongo
```
compiling...
starting proxy...
  proxy frontend 10000 -> 10.0.1.17:20000
  proxy api 10001 -> 10.0.1.17:20001
  proxy service1 10002 -> 10.0.1.17:20002
  proxy service2 10003 -> 10.0.1.17:20003
  proxy backend 10004 -> 10.0.1.17:20004
  proxy redis 10011 -> 10.0.1.17:6739
  proxy mongo 10012 -> 10.0.1.17:27017
starting shell..
? fuge> start mongo
running: mongo
running:  PROXY_HOST=127.0.0.1 SERVICE_HOST=0.0.0.0 frontend_PORT=10000 api_PORT=10001 service1_PORT=10002 service2_PORT=10003 backend_PORT=10004 redis_PORT=10011 mongo_PORT=10012 SERVICE_PORT=27017  exec docker run  -p 10012:27017 -v db:/data/db -e 10012=27017 mongo:3.2
? fuge> [mongo - 16972]: docker: Error response from daemon: driver failed programming external connectivity on endpoint insane_khorana (da097db0a490dff2ddb1812b7aee920eb7664c2db021deb697056e67eda80313): Error starting userland proxy: listen tcp 0.0.0.0:10012: bind: address already in use.
process exit [16972]: mongo

```

The output from  sudo netstat -nl -p tcp  | grep 10012 is
`tcp6       0      0 :::10012                :::*                    LISTEN      15961/node `

This is the pid for the fuge node process.

What I think is happening is that fuge is already bound to the port and when docker tries to bind it to the same port, it throws the error.

I tried using expose like below
```
mongo:
  image: mongo:3.2
  constainer_name: mongo
  expose:
     - 10012
  volumes:
     - db:/data/db
```

The docker image runs now. But the mapping does not happen and hence I can't use it in other services.
